[package]
name = "wgsl_study"
version = "0.1.0"
edition = "2021"

[dependencies]
legion = "0.4.0"
wgpu = "0.20.1"
winit = "0.29.15"
nalgebra = "0.33.0"
cfg-if = "1.0.0"
pollster = "0.3.0"
egui = "0.28.1"
egui-wgpu = "0.28.1"
egui-winit = "0.28.1"

[[example]]
name = "hello_world"
path = "examples/hello_world.rs"